### ISSUE TITLE
希望增加快捷键操作

### ISSUE THREAD

**Issue by MoYuan-CN** [sanmusen214/web_lyric_editor#1]
整体用下来感觉不错，先给作者点个 Star
美中不足的是不能使用快捷键操作音乐控件
例如：空格 -> 开始/暂停，左右键 -> -3s/+3s
如果能加上就好极了

**Comment by aiaou** [comment]
我个人的用法是回车是确定时间，可能的话请考虑下。

**Comment by sanmusen214** [comment]
快捷操作加上了，目前加了和歌曲时间以及歌词时间戳相关的操作，具体可以看README。
